services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: shh
      POSTGRES_DB: crema
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

